In [2]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

# 5.1 pandas 자료 구조 소개

## 5.1.1 Series

In [3]:
obj = Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [11]:
obj2['d'] = 6

In [12]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2

True

In [17]:
'e' in obj2

False

In [18]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [19]:
obj3 = Series(sdata)

In [20]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [21]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [22]:
obj4 = Series(sdata, index=states)

In [23]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [26]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [30]:
obj4.name = 'population'

In [31]:
obj4.index.name = 'state'

In [32]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [33]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [34]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## 5.1.2 DataFrame

In [35]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [36]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [37]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [38]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                  index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [39]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [40]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [41]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [42]:
frame2.ix['three']

C:\Users\Yulma\Anaconda2\envs\python36\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [43]:
frame2['debt'] = 16.5

In [44]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [45]:
frame2['debt'] = np.arange(5.)

In [46]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [47]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [48]:
frame2['debt'] = val

In [49]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [50]:
frame2['eastern'] = frame2.state == 'Ohio'

In [51]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [52]:
del frame2['eastern']

In [53]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [54]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [55]:
frame3 = DataFrame(pop)

In [56]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [57]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [58]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [59]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [60]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [65]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [67]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [68]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

DataFrame 생성자에서 사용 가능한 입력 데이터

형|설명
:---|:---
2차원 ndarray|데이터를 담고 있는 행렬. 선택적으로 로우와 칼럼의 이름을 전달할 수 있다.
배열, 리스트, 튜플의 사전 | 사전의 모든 항목은 같은 길이를 가져야 하며, 각 항목의 내용이 DataFrame의 칼럼이 된다.
NumPy의 구조화 배열 | 배열의 사전과 같은 방식으로 취급된다.
Series 사전 | Series의 각 값이 칼럼이 된다. 명시적으로 색인을 남겨주지 않으면 각 Series의 색인이 하나로 합쳐져서 로우의 색인이 된다.
사전의 사전 | 내무에 있는 사전이 칼럼이 된다. 키 값은 'Series의 사전'과 마찬가지로 합쳐져 로우의 색인이 된다.
사전이나 Series의 리스트 | 리스트의 각 항목이 DataFrame의 로우가 된다. 합쳐진 사전의 키 값이나 Series의 색인이 DataFrame 칼럼의 이름이 된다.
리스트나 튜플의 리스트 | '2차원 ndarray'와 같은 방식으로 취급된다.
다른 DataFrame | 색인이 따로 지정되지 않는다면 DataFrmae의 색인이 그대로 사용된다.
NumPy MaskedArray | '2차원 ndarray'와 같은 방식으로 취급되지만 마스크 값은 반환되는 DataFrmae에서 NA값이 된다.

## 5.1.3 색인 객체

In [70]:
obj = Series(range(3), index = ['a', 'b', 'c'])

In [71]:
index = obj.index

In [72]:
index

Index(['a', 'b', 'c'], dtype='object')

In [73]:
index[1:]

Index(['b', 'c'], dtype='object')

In [75]:
index[1] = 'd' # 색인(index) 개체는 변경할 수 없다

TypeError: Index does not support mutable operations

In [76]:
index = pd.Index(np.arange(3))

In [77]:
obj2 = Series([1.5, -2.5, 0], index = index)

In [78]:
obj2.index is index

True

pandas의 주요 Index 객체

클래스 | 설명
:---|:---
Index | 가장 일반적인 Index 객체이며, 파이썬 객체의 NumPy 배열 형식으로 축의 이름을 표현한다.
Int64Index | 정수 값을 위한 특수한 Index
MultiIndex | 단일 축에 여러 단계의 색인을 표현하는 계층적 색인 객체, 튜플의 배열과 유사하다고 볼 수 있다.
DatetimeIndex | 나노초 차임스탬프를 저장한다(NumPy의 datetime64 dtype으로 표현된다).
PeriodIndex | 기간 데이터를 위한 특수한 Index

In [79]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [81]:
'Ohio' in frame3.columns

True

In [82]:
2003 in frame3.index

False

색인 메서드와 속성

메서드 | 설명
:---|:---
append | 추가적인 Index 객체를 덧붙여 새로운 색인을 반환한다.
diff | 색인의 차집합을 반환한다.
intersection | 색인의 교집합을 반환한다.
union | 색인의 합집합을 반환한다,
isin | 넘겨받은 갓이 해당 색인 위치에 존재하는지 알려주는 불리언 배열을 반환한다.
delete | i 위치의 색인이 삭제된 새로운 색인을 반환한다.
drop | 넘겨받은 값이 삭제된 새로운 색인을 반환한다.
insert | i 위치에 값이 추가된 새로운 색인을 반환한다.
is_monotonic | 색인이 단조성을 가진다면 True를 반환한다.
is_unique | 중복되는 색인이 없다면 True를 반환한다.
unique | 색인에서 중복되는 요소를 제거하고 유일한 값만을 반환한다.

# 5.2 핵심 기능

## 5.2.1 재색인

In [83]:
obj = Series([4.5, 7.2, -5.3, 3.6], index = ('d', 'b', 'a', 'c'))

In [84]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [86]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e']) # 새로운 색인에 맞게 재배열, 없는 색인값은 비어있는 값을 새로 추가

In [87]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [89]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value = 0) # fill_value 누락된 값을 채워넣음

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [90]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [92]:
obj3.reindex(range(6), method = 'ffill') # ffill 앞의 값으로 누락된 값을 채워 넣음

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

reindex 메서드(보간) 옵션

인자 | 설명
:---|:---
ffill 또는 pad | 앞의 값으로 채워 넣는다.
bfill 또는 backfill | 뒤의 값으로 채워 넣는다.

In [114]:
frame = DataFrame(np.arange(9).reshape((3, 3)), index = ['a', 'c', 'd'], columns = ['Ohio', 'Texas', 'California'])

In [115]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [116]:
frame2 = frame.reindex(index = ['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [117]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [120]:
frame.reindex(index = ['a', 'b', 'c', 'd'],  method = 'ffill', columns = states)

ValueError: index must be monotonic increasing or decreasing

In [121]:
frame.ix[['a', 'b', 'c', 'd'], states]

C:\Users\Yulma\Anaconda2\envs\python36\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0